/* originales
dda_id      dda_nombre                     dda_expresion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dda_tipo dda_obs                                                                                              dda_default                                                                                                                                                                                                                                                     dda_alta_fecha          dda_modi_fecha          dda_baja_fecha          dda_usu_id  dda_filler                                                                                                                                                                                                                                                     
----------- ------------------------------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ---------------------------------------------------------------------------------------------------- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----------------------- ----------------------- ----------------------- ----------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
          1 Cliente-Monto Deuda Vencida    (isnull((SELECT SUM(dbo.emx_f_pasar_a_moneda_pais(cuentas.cta_deuda_venc,cuentas.cta_mon)) FROM cuentas WHERE cuentas.cta_per = wf_vw_dic_datos.cta_per AND cuentas.cta_baja_fecha IS NULL), 0))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 N                                                                                                             10                                                                                                                                                                                                                                                              2005-08-29 00:00:00.000 2009-10-05 19:19:58.283                    NULL           1 NULL                                                                                                                                                                                                                                                           
         79 Cliente-Monto Deuda Total      (SELECT SUM(dbo.emx_f_pasar_a_moneda_pais(cuentas.cta_deuda_venc+case when cuentas.cta_deuda_a_venc>0 then cuentas.cta_deuda_a_venc else 0 end,cuentas.cta_mon)) FROM cuentas WHERE cuentas.cta_per = wf_vw_dic_datos.cta_per AND cuentas.cta_baja_fecha IS NULL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                N        Deuda Total del Cliente                                                                              0                                                                                                                                                                                                                                                               2007-01-16 00:00:00.000                    NULL                    NULL           1 NULL                                                                                                                                                                                                                                                           
(2 rows affected)

SELECT top 100 * FROM wf_vw_dic_datos WHERE cta_cat = 2 AND (isnull((datediff(dd,ISNULL((SELECT MIN(a.cta_fec_vto) FROM cuentas a WHERE a.cta_per=wf_vw_dic_datos.cta_per AND a.cta_fec_vto IS NOT NULL AND a.cta_baja_fecha IS NULL),par_fec_proceso),par_fec_proceso)), 0))  >  10 AND (SELECT SUM(dbo.emx_f_pasar_a_moneda_pais(cuentas.cta_deuda_venc+case when cuentas.cta_deuda_a_venc>0 then cuentas.cta_deuda_a_venc else 0 end,cuentas.cta_mon)) FROM cuentas WHERE cuentas.cta_per = wf_vw_dic_datos.cta_per AND cuentas.cta_baja_fecha IS NULL)  >  CONVERT(Decimal(9,2),'500.00') AND (isnull((select case count (*) when 0 then 'NO' else 'SI' end from personas a inner join per_tel b on a.per_id = b.pte_per where b.pte_baja_fecha is null and wf_vw_dic_datos.cta_per = a.per_id), 'N'))  =  'SI' AND (isnull((SELECT SUM(dbo.emx_f_pasar_a_moneda_pais(cuentas.cta_deuda_venc,cuentas.cta_mon)) FROM cuentas WHERE cuentas.cta_per = wf_vw_dic_datos.cta_per AND cuentas.cta_baja_fecha IS NULL), 0))  >  CONVERT(Decimal(9,2),'50.00') 
SELECT top 100 * FROM wf_vw_dic_datos WHERE cta_cat = 2 AND (isnull((datediff(dd,ISNULL((SELECT MIN(a.cta_fec_vto) FROM cuentas a WHERE a.cta_per=wf_vw_dic_datos.cta_per AND a.cta_fec_vto IS NOT NULL AND a.cta_baja_fecha IS NULL),par_fec_proceso),par_fec_proceso)), 0))  >  10 AND (SELECT per_deuda_total FROM persona_deuda WHERE per_id = wf_vw_dic_datos.cta_per)  >  CONVERT(Decimal(9,2),'500.00') AND (isnull((select case count (*) when 0 then 'NO' else 'SI' end from personas a inner join per_tel b on a.per_id = b.pte_per where b.pte_baja_fecha is null and wf_vw_dic_datos.cta_per = a.per_id), 'N'))  =  'SI' AND (SELECT per_deuda_venc FROM persona_deuda WHERE per_id = wf_vw_dic_datos.cta_per)  >  CONVERT(Decimal(9,2),'50.00')
*/


UPDATE
  wf_dic_datos
SET
  dda_expresion = '(SELECT per_deuda_venc FROM persona_deuda WHERE per_id = wf_vw_dic_datos.cta_per)',
  dda_modi_fecha = GETDATE()
WHERE
  dda_nombre = 'Cliente-Monto Deuda Vencida' AND
  dda_baja_fecha IS NULL



UPDATE
  wf_dic_datos
SET
  dda_expresion = '(SELECT per_deuda_total FROM persona_deuda WHERE per_id = wf_vw_dic_datos.cta_per)',
  dda_modi_fecha = GETDATE()
WHERE
  dda_nombre = 'Cliente-Monto Deuda Total' AND
  dda_baja_fecha IS NULL



